FROM gradle:8.12.0-jdk17-alpine@sha256:5239bc3f0697647f7747ac3289db5bacd5ad70eb7328a2e404d12836bd547e4c as build

ENV SPRING_PETCLINIC_SHA256SUM="3bdd29e6e5fe17d17e36b09021ac1a22c5c8cdef7610448fc4323ffceee7913f"
SHELL ["/bin/ash", "-o", "pipefail", "-c"]

WORKDIR /project
COPY . /project
RUN --mount=type=cache,target=/root/.gradle ./gradlew build -x test -x processTestAot
RUN sha256sum ./build/libs/*.jar
RUN echo "${SPRING_PETCLINIC_SHA256SUM} ./build/libs/spring-petclinic-3.4.0.jar" | sha256sum --check --status

FROM bellsoft/liberica-openjre-alpine-musl:17.0.14@sha256:652de1188aba3d475cbae2d4c47b470188fc2aff227bf68a7e785ead86090168
WORKDIR /app
RUN addgroup --system javauser && adduser -S -s /bin/false -G javauser javauser
COPY --from=build /project/target/spring-petclinic*.jar /app/java-application.jar
RUN chown -R javauser:javauser /app
USER javauser

CMD ["java", "-jar", "java-application.jar"]
